[package]
name = "rocket-rust"
version = "0.2.0"
edition = "2021"
authors = ["Gavrilyuk Denis"]
description = "RocketChat API Implemented in Rust"
repository = "https://github.com/karpa4o4/rocket-rust"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
reqwest = { version = "0.11.12", features = ["blocking", "json"] }
serde = { version = "1.0.145", features = ["derive"] }
