name: Build and check runner

on: [push]

jobs:
  linter:
    name: Build and check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build

      - name: Check
        run: cargo check
